FROM golang:1.25-alpine

RUN apk add --no-cache git gcc musl-dev

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", "air.toml"]